### ISSUE TITLE
Allow to import the main module in tests

### ISSUE THREAD

**Issue by michallepicki** [gfngfn/Sesterl#19]
Hi!

I am wondering what is the purpose of the `main_module` setting in the yaml configuration file. From what I can tell:
1. This value is not used when generating the rebar.config file
2. Compiler expects to find a module with that name in any of the source files and errors if not found
3. ~Compiler uses this name to prefix all Erlang module names (including the main module itself, making it e.g. App.App)~ edit: i was wrong, the prefix is derived from package name, no issue here
4. This module cannot be imported in any other modules
5. There's currently no way to have a project with just one module and a test for that module in another file

Are all of the above observations as per design, or are any of them just by coincidence and possible bugs? Thanks!

**Comment by michallepicki** [comment]
Example project: https://github.com/michallepicki/test_sesterl_proj

**Comment by michallepicki** [comment]
If that is expected and simplifies dependency tracking then I think this is fine, maybe just needs to be mentioned in readme?

**Comment by gfngfn** [comment]
Thank you for finding this behavior and reporting it. The behavior seems (at least for me) to be a kind of corner-case bug of the specification, not of the implementation.

Though it hasn’t been documented yet, the *main module* of a package is defined to be the sole module visible from the outside of the package. Therefore, the notion of main modules makes sense for building libraries, not for applications. But currently, it is required to be specified for applications as well.

What causes the problem is the procedure of the compilation of a package; it has the following steps:

1. parses all the source files (and possibly all the test files);
2. sorts the files *other than the one that defines the main module* in the topological order based on the dependency among them specified by `import`;
3. performs their type checking and compilation in order; and
4. finally performs the type checking and the compilation of the main module.

The problem seems to occur in the 3rd step since test files cannot refer to the main module.

We have the following choices:

1. re-design the specification of the procedure, or
2. just document that the main module cannot be referred to from other modules within the package.

The first choice seems preferable to me, but designing a better procedure may not be so trivial. What requires the separate step for checking the main module is the constraint of the signature matching; the signature required for the main module should be independent of the other modules within the package.

The solution may not be so obvious, but thank you for bringing up the issue!

**Comment by gfngfn** [comment]
Maybe modifying the compilation procedure to the following would remedy the problem:

1. parses all the source files (and possibly all the test files);
2. sorts *all the files* in the topological order based on the dependency among them specified by `import`;
3. performs their type checking and compilation in order; and
4. checks that the signature required for the main module can be elaborated by using the type environment containing only the member of the libraries on which the currently checked package depends.

**Comment by michallepicki** [comment]
Hi! I am glad my learnings are somewhat useful and not just annoying.

You're saying that

> the signature required for the main module should be independent of the other modules within the package.

and potentially to:

> check that the signature required for the main module can be elaborated by using the type environment containing only the member of the libraries on which the currently checked package depends.

Can I ask why this requirement is placed? Is this to optimize compilation or put a design restriction on library authors? (E.g. so that a library package has to expose all of its interface visible for other libraries only through the main module)

**Comment by gfngfn** [comment]
> Can I ask why this requirement is placed?

Oh, I notice that I haven’t explicitly explained why I place the requirement that only one module per package, which is called the main module, be public and that the signature for the main module is thereby obliged to be independent of the other private modules.

This requirement is intended to be useful for:

- distinguishing whether each module of the package is public from the outside or public only to other modules within the package, and
- saving the global namespace.

**Comment by michallepicki** [comment]
OK, I now understand what you meant by saying that it

> is defined to be the sole module visible from the outside of the package.

Thank you for re-iterating.

I think importing the main module might be only useful from tests, so possibly it is an option to perform the currently used procedure but add an additonal tests typechecking step: first compiling just the source (non test) files with the current procedure and only after that extending the typing environment to typecheck test files.

**Comment by gfngfn** [comment]
> possibly it is an option to perform the currently used procedure but add an additonal tests typechecking step

This idea seems very reasonable! I will use it as a reference. Thank you for the suggestion!

**Comment by gfngfn** [comment]
Seems fixed by #47. Thank you for reporting!
